from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]

DATA_DIR = PROJECT_ROOT / "data"
ARTIFACTS_DIR = PROJECT_ROOT / "artifacts"
MODELS_DIR = PROJECT_ROOT / "models"
LOGS_DIR = PROJECT_ROOT / "logs"

RAW_DATA_FILE = "insurance.csv"
RAW_DATA_PATH = DATA_DIR / RAW_DATA_FILE

INGESTED_TRAIN_FILE = "train.csv"
INGESTED_TRAIN_PATH = ARTIFACTS_DIR / INGESTED_TRAIN_FILE

BEST_MODEL_FILENAME = "best_insurance_model.pkl"
BEST_MODEL_PATH = MODELS_DIR / BEST_MODEL_FILENAME

DEFAULT_LOG_FILE = "app.log"
DEFAULT_LOG_PATH = LOGS_DIR / DEFAULT_LOG_FILE